services:

  clientes:
    build: ./clientes
    ports:
      - "5002:5000"
    env_file:
      - .env

  hoteles:
    build: ./hoteles
    ports:
      - "5001:5000"
    env_file:
      - .env

      

  mysql_clientes:
   image: mysql:8.0
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: clientes

   ports:
    - "3306:3306"
   volumes:
    - mysql_clientes_data:/var/lib/mysql

  mysql_hoteles:
   image: mysql:8.0
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: hoteles

   ports:
    - "3307:3306"
   volumes:
    - mysql_hoteles_data:/var/lib/mysql



volumes:
  mysql_clientes_data:
  mysql_hoteles_data:
  



  